---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-bionic
    image: docker.io/library/ubuntu:bionic
provisioner:
  name: ansible
verifier:
  name: testinfra
